# This file may be used to create an environment using:
# $ conda env create --name <env> --file conda_recipe/environment.yml
# (This file must be named <something>.yml)
channels:
 - conda-forge
 - pytorch
dependencies:
 - astunparse
 - numpy
 - ninja
 - pyyaml
 - mkl
 - mkl-include
 - setuptools
 - cmake
 - cffi
 - typing_extensions
 - future
 - six
 - requests
 - dataclasses
 - magma-cuda110